### ISSUE TITLE
Notebook Saved State

### ISSUE THREAD

**Issue by pbeens** [callysto/basketball-and-data-science#16]
I'm going to make sure each notebook is saved with the outputs cleared. I feel this will be better for doing the demos in front of the students and for class discussions about "what does this code do?". 

Any reasons why I should do the opposite?

**Comment by misterhay** [comment]
You're exactly right, we should make sure the outputs are cleared. I've written a Python script if we want to automate that: https://gist.github.com/misterhay/62f2dbfffd9b66288d54b25607a8717a

**Comment by pbeens** [comment]
Great, thanks. 

And thanks for the script. One little change I made was to swap out:

`notebook_name = filename[:-6]`

for 

`notebook_name, extension = os.path.splitext(filename)`

Seems cleaner to me.
